=== RexAI/fbdoc/share/xml/news.dtd
<!-- $FreeBSD$ -->

<!ENTITY lists 'http://lists.freebsd.org/pipermail'>
<!ENTITY lists.announce '&lists;/freebsd-announce'>
<!ENTITY lists.current '&lists;/freebsd-current'>
<!ENTITY lists.stable '&lists;/freebsd-stable'>
<!ENTITY lists.ports-announce '&lists;/freebsd-ports-announce'>
<!ENTITY lists.pkg '&lists;/freebsd-pkg'>

<!ELEMENT news (cvs:keyword?, year)+>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  id		ID	#IMPLIED
>

<!ELEMENT year (name, (month)+)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT month (name, (day)+)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ELEMENT day (name, (event)+)>
<!ATTLIST day
  id		ID	#IMPLIED
>

<!ELEMENT event ((title)?, (p)+)>
<!ATTLIST event
  id		ID	#IMPLIED
>

<!ELEMENT title (#PCDATA | a)*>
<!ATTLIST title
  id		ID	#IMPLIED
>

<!ELEMENT p (#PCDATA | a | i)*>
<!ATTLIST p
  id		ID	#IMPLIED
>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ELEMENT i (#PCDATA)>
<!ATTLIST i
  id		ID	#IMPLIED
>

<!ENTITY % cvs
 PUBLIC "-//FreeBSD//DTD FreeBSD CVS Keywords//EN"
	"http://www.FreeBSD.org/XML/share/xml/cvs.dtd">
%cvs;

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/share/xml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/lang/share/xml/l10n.ent">
%l10n.ent;

<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Common Entities//EN"
        "http://www.FreeBSD.org/XML/share/xml/l10n.ent">
%l10n-common.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== RexAI/fbdoc/de_DE.ISO8859-1/htdocs/news/2006/news.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE news PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for News//EN"
                      "http://www.FreeBSD.org/XML/share/xml/news.dtd">
<!--
     $FreeBSD$
     $FreeBSDde: de-www/news/2006/news.xml,v 1.2 2008/03/01 16:00:16 jkois Exp $
     basiert auf: 1.2
-->

<!-- Simple schema for FreeBSD Project news.

     Divide time in to <year>, <month>, and <day> elements, each of which
     has a <name>.

     each <day> element contains one or more <event> elements.

     Each <event> contains an optional <title>, and then a <p>.  <p> elements
     can contain <a> anchors.  Within the "href" attribute of the anchor
     &base; or &enbase; will be replaced with the base URI necessary to reach the FreeBSD
     document root, and should always be used to start URLs at www.FreeBSD.org
     or one of the mirrors.

     Use the <title> element if the <p> content is lengthy.  When generating
     synopses of this information (e.g., for syndication using RDF files),
     the contents of <title> will be preferred over <p>.
-->

<news>
    <cvs:keyword xmlns:cvs="http://www.FreeBSD.org/XML/CVS">
      $FreeBSD$
    </cvs:keyword>

  <year>
    <name>2006</name>

    <month>
      <name>12</name>

      <day>
	<name>27</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:jls@FreeBSD.org">Jordan Sissel</a> (src)</p>
	</event>

	<event>
	  <title>FreeBSD&nbsp;6.2-RC2 verfügbar</title>

	  <p>Der zweite Release Candidate für FreeBSD&nbsp;6.2 ist
	    <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2006-December/031742.html">
	    verfügbar</a>.  Die ISO-Images für alle Tier-1-Plattformen finden
	    Sie wie immer auf den <a
	    href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    FreeBSD Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>26</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:dryice@FreeBSD.org">Dryice Liu</a> (ports)</p>
	</event>
      </day>

      <day>
	<name>22</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:nox@FreeBSD.org">Juergen Lock</a> (ports)</p>
	</event>
      </day>

      <day>
	<name>10</name>

	<event>
	  <title>Podcast-Interview mit dem FreeBSD-Entwickler
	    Joseph Koshy</title>

	  <p>In seinem aktuellen <a
	    href="http://bsdtalk.blogspot.com/">bsdtalk</a>-Podcast
	    spricht Will Backman mit dem FreeBSD-Entwickler
	    Joseph Koshy über seine aktuelle Arbeit an libElf.
	    Dieser Podcast kann von <a
	    href="http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk087.mp3">
	    http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk087.mp3</a>
	    heruntergeladen werden.</p>
	</event>
      </day>

      <day>
	<name>7</name>

	<event>
	  <title>Podcast-Interview mit dem FreeBSD-Entwickler
	    Developer Kip Macy</title>

	  <p>In seinem aktuellen <a
	    href="http://bsdtalk.blogspot.com/">bsdtalk</a>-Podcast
	    spricht Will Backman mit dem FreeBSD-Entwickler Kip Macy
	    über die FreeBSD/sun4v-Portierung. Dieser Podcast
	    ist unter <a
	    href="http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk086.mp3">
	    http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk086.mp3</a>
	    verfügbar.</p>
	</event>
      </day>

      <day>
	<name>5</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:nivit@FreeBSD.org">Nicola Vitale</a> (ports)</p>
	</event>

	<event>
	  <title>Neuer Committer: <a
	    href="mailto:gabor@FreeBSD.org">G&aacute;bor Kövesd&aacute;n</a>
	    (ports).  Ein SoC2006-Teilnehmer.</title>

	  <p><a
	    href="mailto:gabor@FreeBSD.org">G&aacute;bor Kövesd&aacute;n</a>,
	    ein Student, der im letzten Jahr an Google's Summer
	    of Code teilgenommen hat, hat das FreeBSD Project
	    auch danach weiter unterstützt und wurde nun
	    als neuer ports/-Committer in das Projekt aufgenommen.</p>
	</event>
      </day>

      <day>
	<name>1</name>

	<event>
	  <title>Podcast-Interview mit dem FreeBSD-Entwickler
	    Tom McLaughlin</title>

	  <p>In seinem aktuellen <a
	    href="http://bsdtalk.blogspot.com/">bsdtalk</a>-Podcast
	    spricht Will Backman mit dem FreeBSD-Entwickler
	    Tom McLaughlin über das BSD# Project und den
	    Einsatz von Mono unter FreeBSD.  Dieser Podcast kann
	    von <a
	    href="http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk085.mp3">
	    http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk085.mp3</a>
	    heruntergeladen werden.</p>
	</event>
      </day>
    </month>

    <month>
      <name>11</name>

      <day>
	<name>29</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:lx@FreeBSD.org">David Thiel</a> (ports)</p>
	</event>

	<event>
	  <title>Podcast-Interview mit dem FreeBSD Release Engineer
	    Bruce Mah</title>

	  <p>In seinem aktuellen <a
	    href="http://bsdtalk.blogspot.com/">bsdtalk</a>-Podcast
	    spricht Will Backman mit dem FreeBSD Release Engineer
	    Bruce Mah über die bevorstehende
	    FreeBSD-Version&nbsp;6.2.  Dieser Podcast kann von <a
	    href="http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk084.mp3">
	    http://cisx1.uma.maine.edu/~wbackman/bsdtalk/bsdtalk084.mp3</a>
	    heruntergeladen werden.</p>
	</event>
      </day>

      <day>
	<name>17</name>

	<event>
	  <title>FreeBSD&nbsp;6.2-RC1 verfügbar</title>

	  <p>Der erste Release Candidate für
	    FreeBSD&nbsp;6.2 ist nun <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2006-November/030811.html">
	    verfügbar</a>.  ISO-Images für alle
	    Tier-1-Architekturen finden Sie inzwischen auf
	    den meisten <a
	    href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>16</name>

	<event>
	  <title>FreeBSD Foundation startet Spendenkampagne</title>

	  <p>Die <a
	    href="http://www.freebsdfoundation.org/">FreeBSD Foundation</a>
	    hat ihre <a
	    href="http://www.freebsdfoundation.org/donate/">Fall
	    Fundraising Campaign</a> gestartet.  Das Ergebnis
	    dieser Spendenkampagne wird das Budget der Foundation
	    für das nächste Jahr maßgeblich
	    bestimmen.</p>
	</event>
      </day>

      <day>
	<name>14</name>

	<event>
	  <title>Umzug der FreeBSD.org-Server verschoben</title>

	  <p>Der ursprünglich für Montag, den
	    13. November 2006 vorgesehene Umzug der
	    FreeBSD.org-Server wurde verschoben.  Der neue
	    geplante Umzugstermin ist Freitag, den
	    17. November 2006 (US Pacific Standard Time).</p>
	</event>
      </day>

      <day>
	<name>12</name>

	<event>
	  <title>FreeBSD/sun4v-Installations- und/oder Live-CD
	    verfügbar</title>

	  <p>Für die Portierung von FreeBSD auf die
	    UltraSparc-T1-Architektur von Sun ist ein
	    installierbares ISO-Image verfügbar, das
	    sich auch als Live-CD einsetzen lässt.
	    Weitere Informationen finden Sie auf der
	    Seite <a
	    href="&base;/platforms/sun4v.html">FreeBSD/sun4v Project</a>.</p>
	</event>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:koitsu@FreeBSD.org">Jeremy Chadwick</a> (ports)</p>
	</event>
      </day>

      <day>
	<name>7</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:farrokhi@FreeBSD.org">Babak Farrokhi</a> (ports)</p>
	</event>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:laszlof@FreeBSD.org">Frank J. Laszlo</a> (ports)</p>
	</event>
      </day>

      <day>
	<name>5</name>

	<event>
	  <title>Umzug der FreeBSD.org-Server</title>

	  <p>Die für E-Mail, Internet, CVS und so weiter
	    verantwortlichen FreeBSD.org-Server werden in
	    Kürze in ein neues Rechenzentrum
	    übersiedeln.  Derzeit ist der Umzug für
	    Montag, den 13. November 2006 (US Pacific Standard
	    Time) vorgesehen.</p>

	  <p>Während der Vorbereitungen für diesen
	    Umzug kann es zu kurzfristigen Ausfällen
	    von FreeBSD.org-Diensten kommen.  Am Tag des
	    Umzug werden nur die statischen Teile der Webseiten
	    (also nur einfache HTML-Seiten, aber beispielsweise
	    keine CGI-Funktionen) von <a
	    href="http://www.FreeBSD.org/">http://www.FreeBSD.org/</a>
	    funktionieren.</p>
	</event>
      </day>
    </month>

    <month>
      <name>10</name>

      <day>
	<name>31</name>

	<event>
	  <title>FreeBSD 6.2-BETA3 verfügbar</title>

	  <p>Die dritte Betaversion für FreeBSD&nbsp;6.2 ist <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2006-November/030277.html">
	    verfügbar</a>.  Die entsprechenden ISO-Images für
	    alle Tier-1-Plattformen finden Sie auf den verschiedenen <a
	    href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>25</name>

	<event>
	  <title>Summer of Code-Projekte abgeschlossen</title>

	  <p>Das FreeBSD Project freut sich, bekannt geben zu
	    können, dass alle 14 Studenten, die im Rahmen
	    von Google's <a
	    href="&enbase;/projects/summerofcode-2006.html">Summer
	    of Code</a> an FreeBSD gearbeitet haben, ihre Projekte
	    erfolgreich abgeschlossen haben.  Wir gratulieren
	    Mentoren und Studenten und danken <a
	    href="http://www.google.com/bsd">Google</a> für
	    dieses Programm sowie für dessen Finanzierung.</p>
	</event>
      </day>

      <day>
	<name>19</name>

	<event>
	  <title>Statusreport Juni-Oktober 2006</title>

	  <p>Der Statusreport für die Monate
	    Juni-Oktober 2006 mit 49 Einträgen wurde
	    <a
	    href="&enbase;/news/status/report-2006-10-2006-12.html">
	    veröffentlicht</a>.</p>
	</event>
      </day>

      <day>
	<name>14</name>

	<event>
	  <title>GNOME 2.16.1 für FreeBSD freigegeben</title>

	  <p>GNOME 2.16.1 wurde in die FreeBSD Ports-Sammlung
	    aufgenommen.  Die offizielle Ankündigung finden
	    Sie auf der <a
	    href="&enbase;/gnome/index.html">FreeBSD GNOME Homepage</a>.
	    Auf der gleichen Seite finden Sie Informationen zur
	    <a
	    href="&enbase;/gnome/docs/faq216.html">Aktualisierung</a>
	    einer bereits installierten GNOME-Version.</p>
	</event>
      </day>

      <day>
	<name>8</name>
