=== RexAI/fbdoc/share/xml/press.dtd
<!-- $FreeBSD$ -->

<!ELEMENT press (cvs:keyword?, year)+>

<!ELEMENT year (name, (month)+)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT month (name, (story)+)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ENTITY % html.orig PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
%html.orig;

<!ELEMENT story (name, url, site-name, site-url, date, author, (p)+)>
<!ATTLIST storyevent
  id		ID	#IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  id		ID	#IMPLIED
>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url
  id		ID	#IMPLIED
>
<!ELEMENT site-name (#PCDATA)>
<!ATTLIST site-name
  id		ID	#IMPLIED
>
<!ELEMENT site-url (#PCDATA)>
<!ATTLIST site-url
  id		ID	#IMPLIED
>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  id		ID	#IMPLIED
>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  id		ID	#IMPLIED
>

<!ENTITY % cvs
 PUBLIC "-//FreeBSD//DTD FreeBSD CVS Keywords//EN"
	"http://www.FreeBSD.org/XML/share/xml/cvs.dtd">
%cvs;

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/share/xml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/lang/share/xml/l10n.ent">
%l10n.ent;

<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Common Entities//EN"
        "http://www.FreeBSD.org/XML/share/xml/l10n.ent">
%l10n-common.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== RexAI/fbdoc/de_DE.ISO8859-1/share/xml/press.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE press PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Press//EN"
                      "http://www.FreeBSD.org/XML/share/xml/press.dtd">
<!--
 COMMITTERS PLEASE NOTE:
    News articles referenced in this file are also to be archived under
    "freefall:/c/www/bsddoc/press/".
    $FreeBSD$
    $FreeBSDde$
    basiert auf: r42024
-->

<press>
    <cvs:keyword xmlns:cvs="http://www.FreeBSD.org/XML/CVS">
      $FreeBSD$
    </cvs:keyword>

  <year>
    <name>2013</name>
    
    <month>
      <name>6</name>

      <story>
	<name>Fixing Network Attached Storage with commodity hardware
	  and BSD</name>
	<url>http://boingboing.net/2013/06/23/fixing-network-attached-storag.html</url>
	<site-name>Boing Boing</site-name>
	<site-url>http://boingboing.net/</site-url>
	<date>23. Juni 2013</date>
	<author>Ben Laurie</author>
	<p>Ben Laurie beschreibt, warum er ein proprietäres NAS durch ein
	  auf &os; basierendes NAS mit Standardhardware ersetzt hat.</p>
      </story>
    </month>

    <month>
      <name>2</name>

      <story>
	<name>2012 - A BSD Year in Retrospective</name>
	<url>http://www.osnews.com/story/26787/2012_a_BSD_year_in_retrospective</url>
	<site-name>OSnews</site-name>
	<site-url>http://www.osnews.com/</site-url>
	<date>14. Februar 2013</date>
	<author>Julian Djamil</author>
	<p>Ein Rückblick auf die aufregenden Entwicklungen, die 2012 in der
	  BSD-Betriebssystemfamilie stattgefunden haben.  Näher eingegangen
	  wird dabei auf FreeBSD, NetBSD, OpenBSD sowie DragonflyBSD.</p>
      </story>
    </month>

    <month>
      <name>1</name>

      <story>
	<name>A Decade of OS Access-control Extensibility</name>
	<url>https://queue.acm.org/detail.cfm?id=2430732</url>
	<site-name>ACM Queue</site-name>
	<site-url>https://queue.acm.org/</site-url>
	<date>18. Januar 2013</date>
	<author>Robert N. M. Watson</author>
	<p>Wer sich näher mit der Absicherung von Betriebssystemen
	  beschäftigt, ist erstaunt über die zahlreichen in der
	  Praxis eingesetzten Modelle zur Zugangskontrolle.</p>
      </story>
    </month>
  </year>

  <year>
    <name>2012</name>

    <month>
      <name>11</name>

      <story>
	<name>A world without Linux: Where would Apache,
	  Microsoft &mdash; even Apple be today?</name>
	<url>http://www.infoworld.com/d/data-center/world-without-linux-where-would-apache-microsoft-even-apple-be-today-206680</url>
	<site-name>Infoworld</site-name>
	<site-url>http://www.infoworld.com</site-url>
	<date>12. November 2012</date>
	<author>Paul Venezia</author>
	<p>Hätte Linux nicht die Welt erobert, würden wir heute alle FreeBSD
	  verwenden.  Vielleicht sogar auf dem Desktop.</p>
      </story>
    </month>    
    
    <month>
      <name>8</name>

      <story>
	<name>FreeBSD Now Supported on Windows Server Hyper-V Via Beta
	  Release</name>
	<url>http://redmondmag.com/articles/2012/08/09/freebsd-beta-for-windows-server-hyper-v.aspx</url>
	<site-name>Redmondmag</site-name>
	<site-url>http://redmondmag.com</site-url>
	<date>9. August 2012</date>
	<author>Kurt Mackie</author>
	<p>Microsoft hat heute die Betaversion eines Treibers veröffentlicht,
	  mit der erstmals das frei verfügbare FreeBSD 8.2 in einer virtuellen
	  Machine von Microsofts Hyper-V Server installiert werden kann.</p>
      </story>
    </month>

    <month>
      <name>6</name>

      <story>
	<name>X.Org 7.7 Goes Into FreeBSD, KMS Is Ready</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTExNzY</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>11. Juni 2012</date>
	<author>Michael Larabel</author>
	<p>Obwohl X.Org 7.7 erst vor einer Woche erschienen ist, gibt es
	  bereits aktualisierte FreeBSD-Installationspakete.  Die
	  FreeBSD-Entwickler bitten darum, ihnen beim Test dieser Pakete
	  zu helfen.</p>
      </story>

      <story>
	<name>Netflix Open Connect Network: FreeBSD, Not Linux</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTExNDM</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>6. Juni 2012</date>
	<author>Michael Larabel</author>
	<p>Netflix hat mit Open Connect Network sein eigenes CDN
	  (Content Distribution Network) angekündigt.  Doch anstatt
	  auf Linux zu setzen, wurde entschieden, FreeBSD als Basis zu
	  verwenden.</p>
      </story>
    </month>

    <month>
      <name>5</name>

      <story>
	<name>Why Should You Use FreeBSD?  Here's Some Reasons</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTExMDg</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>31. Mai 2012</date>
	<author>Michael Larabel</author>
	<p>FreeBSD fragt, warum Sie FreeBSD verwenden.  David Chisnall
	  vom FreeBSD Project ist gerade dabei, das Werbematerial für
	  dieses führende *BSD-Betriebssystem zu aktualisieren.  Dazu
	  stellt er auf den Mailinglisten die Frage: &quot;Warum
	  verwenden Sie FreeBSD?&quot;</p>
      </story>

      <story>
	<name>Colocation Provider NYI Launches East Coast Mirror for
	  FreeBSD Foundation</name>
	<url>http://www.thewhir.com/web-hosting-news/colocation-provider-nyi-launches-east-coast-mirror-for-freebsd-foundation</url>
	<site-name>The WHIR</site-name>
	<site-url>http://www.thewhir.com</site-url>
	<date>25. Mai 2012</date>
	<author>Nicole Henderson</author>
	<p>Der Hosting-Anbieter NYI hat die Installation eines an der
	  US-Ostküste gelegenen Spiegelservers für die
	  FreeBSD Foundation bekanntgegeben.  &quot;FreeBSD ist eine
	  kritische Komponente in jedem unserer
	  Geschäftsbereiche,&quot; erklärte Phillip Koblence,
	  VP operations, NYI in einer Presseaussendung.  &quot;Wir
	  sehen dieses Projekt als einen Weg, der FreeBSD-Gemeinde,
	  deren Open Source-Projekte es uns erlauben, flexible
	  Lösungen für unsere Kunden anzubieten, etwas
	  zurück zu geben.&quot;</p>
      </story>

      <story>
	<name>FreeBSD and Microsoft Hyper-V Interoperability Expected
	  This Summer</name>
	<url>http://redmondmag.com/articles/2012/05/14/microsoft-hyperv-interoperability.aspx</url>
	<site-name>Redmondmag</site-name>
	<site-url>http://redmondmag.com</site-url>
	<date>14. Mai 2012</date>
	<author>Kurt Mackie</author>
	<p>Microsoft und mehrere seiner Partnerfirmen sind dabei, ein
	  Projekt abzuschliessen, dass Interoperabilität zwischen
	  Windows Server Hyper-V und FreeBSD ermöglichen wird.</p>
      </story>

      <story>
	<name>FreeBSD 10 To Use Clang Compiler, Deprecate GCC</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTEwMjI</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>12. Mai 2012</date>
	<author>Michael Larabel</author>
	<p>Der GCC soll unter FreeBSD in naher Zukunft durch LLVM's
	  Clang-Compiler ersetzt werden.  Auch das Ziel eines GNU-freien
	  C++11-Stacks ist deutlich näher gerückt.  Das Ziel
	  für FreeBSD 10 ist es, Clang als Standard-C/C++-Compiler
	  einzusetzen,  GCC als veraltet zu deklarieren und einen
	  BSD-lizenzierten C++-Stack zu verwenden.</p>
      </story>

      <story>
	<name>FreeBSD Achieved A Lot In Q1'2012</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTEwMjE</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>12. Mai 2012</date>
	<author>Michael Larabel</author>
	<p>In den ersten drei Monaten des Jahres 2012 gab es zahlreiche
	  Fortschritte bei der Weiterentwicklung von FreeBSD.  Dieser
	  Artikel beschreibt einige Hightlights (basierend auf den
	  Informationen des FreeBSD-Statusberichts).</p>
      </story>
    </month>

    <month>
      <name>4</name>

      <story>
	<name>FreeBSD Gets A New X.Org With Intel KMS</name>
	<url>http://www.phoronix.com/scan.php?page=news_item&amp;px=MTA5MTc</url>
	<site-name>phoronix</site-name>
	<site-url>http://www.phoronix.com</site-url>
	<date>23. April 2012</date>
	<author>Michael Larabel</author>
	<p>Das FreeBSD-Team hat ein Update für X.org
	  angekündigt, dass die FreeBSD-Version auf X.org 7.5.2
	  aktualisiert und nun unter anderem auch Intel KMS
	  unterstützt.</p>
      </story>
    </month>

    <month>
      <name>3</name>

      <story>
	<name>Most Reliable Hosting Company Sites in March 2012</name>
	<url>http://news.netcraft.com/archives/2012/04/02/most-reliable-hosting-company-sites-in-march-2012.html</url>
	<site-name>Netcraft Ltd.</site-name>
	<site-url>http://www.netcraft.com/</site-url>
	<date>02. März 2012</date>
	<author>Netcraft</author>
	<p>Drei der 10 zuverlässigsten Webserver im März 2012
	  laufen unter FreeBSD.</p>
      </story>
    </month>

    <month>
      <name>2</name>

      <story>
	<name>PC-BSD 9 review ? to FreeBSD what Ubuntu is to
	  Debian</name>
	<url>http://www.linuxuser.co.uk/reviews/pc-bsd-9-review-to-freebsd-what-ubuntu-is-to-debian/</url>
	<site-name>Linux User &amp; Developer</site-name>
	<site-url>http://www.linuxuser.co.uk</site-url>
	<date>09. Februar 2012</date>
	<author>Koen Vervloesem</author>
	<p>PC-BSD bietet einen voll funktionsfähigen Desktop, der
	  auf dem stabilen FreeBSD basiert und ist daher ideal für
	  die ersten Schritte in die BSD-Welt.</p>
      </story>
    </month>

    <month>
      <name>1</name>

      <story>
	<name>[Review] FreeBSD 9.0</name>
	<url>http://linuxconfig.net/review/freebsd-review/freebsd-9-0-review.html</url>
	<site-name>linuxconfig.net</site-name>
	<site-url>http://linuxconfig.net</site-url>
	<date>10. Januar 2012</date>
	<author>linuxconfig.net</author>
	<p>Dieser Artikel bietet eine Einführung in verschiedene
	  neue Funktionen von FreeBSD 9.0.</p>
      </story>
    </month>
  </year>

  <year>
    <name>2011</name>

    <month>
      <name>11</name>

      <story>
	<name>Why aren't you using FreeBSD?</name>
	<url>http://www.infoworld.com/d/data-center/why-arent-you-using-freebsd-178119?page=0,0</url>
	<site-name>Infoworld</site-name>
	<site-url>http://www.infoworld.com</site-url>
